export const TradeRecordConstants = {
  TradedAt: "交易日期",
  Type: "交易类型",
  Factor: "系数",
  Shares: "发生份额",
  Price: "成交价格",
  Amount: "发生金额",
  Fee: "交易费用",
  Comment: "备注",
  AdjustedAmount: "加权交易金额",
  AdjustedShares: "加权发生份额",
  AdjustedFee: "加权交易费用",
  CumulativeTotalAmount: "当前累计交易金额",
  CumulativeTotalShares: "当前累计发生份额",
  CumulativeCostPrice: "当前成本价格",
} as const;
