export const TradeRecordConstants = {
  TradedAt: "交易日期",
  Type: "交易类型",
  Factor: "系数",
  Shares: "份额变化",
  Price: "成交价格",
  Amount: "金额变化",
  Fee: "费用支出",
  Comment: "备注",
  AdjustedAmount: "加权成本变化",
  AdjustedShares: "加权份额变化",
  AdjustedFee: "加权费用支出",
  CumulativeTotalAmount: "当前累计交易成本",
  CumulativeTotalShares: "当前累计发生份额",
  CumulativeCostPrice: "当前成本价格",
} as const;
