export const TradeRecordConstants = {
  TradedAt: "交易日期",
  Type: "交易类型",
  Factor: "合并笔数",
  Shares: "单笔数量",
  Price: "成交价格",
  Amount: "单笔金额",
  Fee: "单笔费用",
  FeeRate: "费率",
  Comment: "备注",
  AdjustedAmount: "合计金额",
  AdjustedShares: "合计数量",
  AdjustedFee: "合计费用",
  CumulativeTotalAmount: "累计投入",
  CumulativeTotalShares: "当前持仓",
  CumulativeCostPrice: "持仓成本价",
  PositionCostEfficiency: "仓位/成本",
} as const;
